#!/usr/bin/env python3
"""
Command-line utility to run compile or test actions.

This script accepts a single positional argument with two possible values:
'compile' or 'test'. Based on the argument, it executes the corresponding
function, which can be customized to run system commands.
"""

import argparse
import os
import subprocess


def compile() -> None:
    """Run the compile process.

    Modify this function to include the actual compile command and any
    required environment variables.
    """
    # Copy current environment and modify as needed
    # env: Dict[str, str] = os.environ.copy()
    # env["ADD_ENV_VAR_NAME_HERE"] = "value"  # Add your environment variable here

    # Replace with your actual compile command
    def compile_test(test_name: str, suite: str, extra_flags: str = "") -> None:
        process = subprocess.Popen(
            f"g++ -std=c++23 \
                    test_suite/{suite}/{test_name}.cpp -o bin/{suite}/{test_name} {extra_flags}".split(),
            # env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )

        print(f"Compiling: test_suite/{suite}/{test_name}.cpp")
        stdout, stderr = process.communicate()

        if stdout.strip():
            print(stdout)

        if stderr:
            print("Compile stderr:")
            print(stderr)

    os.makedirs('bin/sequential', exist_ok=True)
    os.makedirs('bin/parallel', exist_ok=True)

    # Compilations
    for test in os.listdir("test_suite/sequential"):
        compile_test(test.replace(".cpp", ""), "sequential")
    for test in os.listdir("test_suite/parallel"):
        compile_test(test.replace(".cpp", ""), "parallel", "-fopenmp")


def test(upper_limit: int = 11) -> None:
    """Run the test process.

    Modify this function to include the actual test command and any
    required environment variables.
    """
    # env: Dict[str, str] = os.environ.copy()
    # env["env"] = "value"

    directory = "bin/sequential"
    for test_bin in os.listdir(directory):
        print(f"Testing: {test_bin}")
        print(40*'=')
        for i in range(2, upper_limit+1):
            N = 1 << i
            print(f"N = {N}")
            for j in range(1, 9):
                tile_size = 1 << j
                print(f"tile = {tile_size} ", end='')

                for _ in range(10):
                    process = subprocess.Popen(
                        f"./{directory}/{test_bin} {N} {tile_size}".split(),
                        # env=env,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        text=True,
                    )

                    stdout, stderr = process.communicate()

                    print(stdout, end='')

                    if stderr:
                        print("Test stderr:")
                        print(stderr)
        print(40*'=')


def parallel_test() -> None:
    env: dict[str, str] = os.environ.copy()
    env["OMP_NUM_THREADS"] = ""

    for test_bin in os.listdir('bin/parallel/'):
        for i in range(2, 12):
            N = 1 << i
            print(f"N = {N}")
            for j in range(1, 9):
                tile_size = 1 << j
                print(f"tile = {tile_size} ", end='')

                for _ in range(10):
                    process = subprocess.Popen(
                        f"./bin/{test_bin} {N} {tile_size}".split(),
                        # env=env,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        text=True,
                    )

                    stdout, stderr = process.communicate()

                    print(stdout, end='')

                    if stderr:
                        print("Test stderr:")
                        print(stderr)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        argparse.Namespace: Parsed arguments with the selected action.
    """
    parser = argparse.ArgumentParser(
        description="Run compile or test actions.")
    parser.add_argument(
        "action",
        choices=["compile", "test", "parallel_test"],
        help="Action to perform: 'compile', 'test' or 'parallel_test'.",
    )
    parser.add_argument("--max_N", type=int, default=11,
                        help="Maximum size of matrix.")

    return parser.parse_args()


def main() -> None:
    """Main entry point of the script."""
    args = parse_args()
    upper_limit = args.max_N

    if args.action == "compile":
        compile()
    elif args.action == "test":
        test(upper_limit)
    elif args.action == "parallel_test":
        parallel_test()
    else:
        # This branch should not be reached due to argparse choices
        raise ValueError(f"Unsupported action: {args.action}")


if __name__ == "__main__":
    main()
